name: server.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      # Bước 1: Checkout mã nguồn
      - uses: actions/checkout@v2

      # Bước 2: Cài đặt Node.js với phiên bản được chỉ định từ matrix
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Bước 3: Cài đặt các dependencies
      - name: Install dependencies
        run: npm install

      # Bước 4: Chạy test (hoặc build)
      - name: Run tests
        run: npm test
